secrets:
  sentry_dsn:
    file: "./.secrets/sentry_dsn"
  database_username:
    file: "./.secrets/database_username"
  database_password:
    file: "./.secrets/database_password"
  jwt_public_key:
    file: "./.secrets/jwt_public_key.pem"
  jwt_private_key:
    file: "./.secrets/jwt_private_key.pem"
  image_api_key:
    file: "./.secrets/image_api_key"

services:
  mensatt:
    build:
      target: dev
    volumes:
      - .:/opt/mensatt
    secrets:
      - "sentry_dsn"
      - "database_username"
      - "database_password"
      - "jwt_public_key"
      - "jwt_private_key"
      - "image_api_key"
    environment:
      ENVIRONMENT: local
      HOST: 0.0.0.0
      PORT: 4000
      MAX_CONNECTIONS: 90
      DEBUG_ENABLED: true
      DATABASE_HOST: postgres
      DATABASE_NAME: mensatt
      DATABASE_USERNAME_FILE: /run/secrets/database_username
      DATABASE_PASSWORD_FILE: /run/secrets/database_password
      SENTRY_DSN_FILE: /run/secrets/sentry_dsn
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
      JWT_ALGORITHM: RS256
      JWT_TIMEOUT_SEC: 525600
      IMAGE_API_URL: https://localhost:3000/
      IMAGE_API_KEY_FILE: /run/secrets/image_api_key
    ports:
      - "4000:4000"
    links:
      - postgres

  postgres:
    image: postgres:14.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    secrets:
      - "database_username"
      - "database_password"
    environment:
      POSTGRES_DB: mensatt
      POSTGRES_USER_FILE: /run/secrets/database_username
      POSTGRES_PASSWORD_FILE: /run/secrets/database_password
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres-data:
  asset-data:
