version: "3.9"

services:
  postgresql_database:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=mensatt
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mensatt
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data: