version: "3.9"

services:
  mensatt:
    build:
      target: dev
    volumes:
      - .:/opt/app/mensatt
    environment:
      HOST: 0.0.0.0
      PORT: 4000
      SERVER_PATH_VERSION: v1
      DEBUG_ENABLED: true
      DATABASE_URL: postgres://mensatt@postgres/mensatt?sslmode=disable
      SENTRY_DSN: https://<token>.ingest.sentry.io/<project>
    ports:
      - "4000:4000"
    links:
      - postgres

  postgres:
    image: postgres:14.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mensatt
      POSTGRES_USER: mensatt
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres-data: