version: "3.9"

secrets:
  sentry_dsn:
    file: "./.secrets/sentry_dsn"
  database_username:
    file: "./.secrets/database_username"
  database_password:
    file: "./.secrets/database_password"
  jwt_public_key:
    file: "./.secrets/jwt_public_key.pem"
  jwt_private_key:
    file: "./.secrets/jwt_private_key.pem"

services:
  mensatt:
    build:
      target: dev
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - .:/opt/app/mensatt
      - asset-data:/opt/app/mensatt/assets
    secrets:
      - "sentry_dsn"
      - "database_username"
      - "database_password"
      - "jwt_public_key"
      - "jwt_private_key"
    environment:
      HOST: 0.0.0.0
      PORT: 4000
      MAX_CONNECTIONS: 90
      SERVER_PATH_VERSION: v1
      DEBUG_ENABLED: true
      DATABASE_HOST: postgres
      DATABASE_NAME: mensatt
      DATABASE_USERNAME_FILE: /run/secrets/database_username
      DATABASE_PASSWORD_FILE: /run/secrets/database_password
      SENTRY_DSN_FILE: /run/secrets/sentry_dsn
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
      JWT_ALGORITHM: RS256
      JWT_TIMEOUT_SEC: 525600
      ASSETS_DIR: /opt/app/mensatt/assets
      IMAGE_PROCESSOR_MAX_OUTPUT_SIZE_MB: 10
      IMAGE_PROCESSOR_MAX_RESOLUTION: 8192
    ports:
      - "4000:4000"
    links:
      - postgres

  postgres:
    image: postgres:14.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    secrets:
      - "database_username"
      - "database_password"
    environment:
      POSTGRES_DB: mensatt
      POSTGRES_USER_FILE: /run/secrets/database_username
      POSTGRES_PASSWORD_FILE: /run/secrets/database_password
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres-data:
  asset-data:
