// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: dish.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDish = `-- name: CreateDish :one
INSERT INTO dish (name)
VALUES ($1)
RETURNING id, name, english_name
`

func (q *Queries) CreateDish(ctx context.Context, name string) (*Dish, error) {
	row := q.db.QueryRow(ctx, createDish, name)
	var i Dish
	err := row.Scan(&i.ID, &i.Name, &i.EnglishName)
	return &i, err
}

const getAllDishes = `-- name: GetAllDishes :many
SELECT id, name, english_name
FROM dish
`

func (q *Queries) GetAllDishes(ctx context.Context) ([]*Dish, error) {
	rows, err := q.db.Query(ctx, getAllDishes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Dish
	for rows.Next() {
		var i Dish
		if err := rows.Scan(&i.ID, &i.Name, &i.EnglishName); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDishByID = `-- name: GetDishByID :one
SELECT id, name, english_name
FROM dish
WHERE id = $1
`

func (q *Queries) GetDishByID(ctx context.Context, id uuid.UUID) (*Dish, error) {
	row := q.db.QueryRow(ctx, getDishByID, id)
	var i Dish
	err := row.Scan(&i.ID, &i.Name, &i.EnglishName)
	return &i, err
}

const updateDish = `-- name: UpdateDish :one
UPDATE dish
SET
    name = COALESCE($2, name)
WHERE id = $1
RETURNING id, name, english_name
`

type UpdateDishParams struct {
	ID   uuid.UUID      `json:"id"`
	Name sql.NullString `json:"name"`
}

func (q *Queries) UpdateDish(ctx context.Context, arg *UpdateDishParams) (*Dish, error) {
	row := q.db.QueryRow(ctx, updateDish, arg.ID, arg.Name)
	var i Dish
	err := row.Scan(&i.ID, &i.Name, &i.EnglishName)
	return &i, err
}
