// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mensatt/backend/internal/database/ent/dish"
	"github.com/mensatt/backend/internal/database/ent/dishalias"
	"github.com/mensatt/backend/internal/database/ent/predicate"
)

// DishAliasUpdate is the builder for updating DishAlias entities.
type DishAliasUpdate struct {
	config
	hooks    []Hook
	mutation *DishAliasMutation
}

// Where appends a list predicates to the DishAliasUpdate builder.
func (dau *DishAliasUpdate) Where(ps ...predicate.DishAlias) *DishAliasUpdate {
	dau.mutation.Where(ps...)
	return dau
}

// SetNormalizedAliasName sets the "normalized_alias_name" field.
func (dau *DishAliasUpdate) SetNormalizedAliasName(s string) *DishAliasUpdate {
	dau.mutation.SetNormalizedAliasName(s)
	return dau
}

// SetDishID sets the "dish" edge to the Dish entity by ID.
func (dau *DishAliasUpdate) SetDishID(id uuid.UUID) *DishAliasUpdate {
	dau.mutation.SetDishID(id)
	return dau
}

// SetDish sets the "dish" edge to the Dish entity.
func (dau *DishAliasUpdate) SetDish(d *Dish) *DishAliasUpdate {
	return dau.SetDishID(d.ID)
}

// Mutation returns the DishAliasMutation object of the builder.
func (dau *DishAliasUpdate) Mutation() *DishAliasMutation {
	return dau.mutation
}

// ClearDish clears the "dish" edge to the Dish entity.
func (dau *DishAliasUpdate) ClearDish() *DishAliasUpdate {
	dau.mutation.ClearDish()
	return dau
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (dau *DishAliasUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, dau.sqlSave, dau.mutation, dau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dau *DishAliasUpdate) SaveX(ctx context.Context) int {
	affected, err := dau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dau *DishAliasUpdate) Exec(ctx context.Context) error {
	_, err := dau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dau *DishAliasUpdate) ExecX(ctx context.Context) {
	if err := dau.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dau *DishAliasUpdate) check() error {
	if v, ok := dau.mutation.NormalizedAliasName(); ok {
		if err := dishalias.NormalizedAliasNameValidator(v); err != nil {
			return &ValidationError{Name: "normalized_alias_name", err: fmt.Errorf(`ent: validator failed for field "DishAlias.normalized_alias_name": %w`, err)}
		}
	}
	if _, ok := dau.mutation.DishID(); dau.mutation.DishCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "DishAlias.dish"`)
	}
	return nil
}

func (dau *DishAliasUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := dau.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(dishalias.Table, dishalias.Columns, sqlgraph.NewFieldSpec(dishalias.FieldID, field.TypeString))
	if ps := dau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dau.mutation.NormalizedAliasName(); ok {
		_spec.SetField(dishalias.FieldNormalizedAliasName, field.TypeString, value)
	}
	if dau.mutation.DishCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dishalias.DishTable,
			Columns: []string{dishalias.DishColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dish.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dau.mutation.DishIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dishalias.DishTable,
			Columns: []string{dishalias.DishColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dish.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, dau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dishalias.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	dau.mutation.done = true
	return n, nil
}

// DishAliasUpdateOne is the builder for updating a single DishAlias entity.
type DishAliasUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DishAliasMutation
}

// SetNormalizedAliasName sets the "normalized_alias_name" field.
func (dauo *DishAliasUpdateOne) SetNormalizedAliasName(s string) *DishAliasUpdateOne {
	dauo.mutation.SetNormalizedAliasName(s)
	return dauo
}

// SetDishID sets the "dish" edge to the Dish entity by ID.
func (dauo *DishAliasUpdateOne) SetDishID(id uuid.UUID) *DishAliasUpdateOne {
	dauo.mutation.SetDishID(id)
	return dauo
}

// SetDish sets the "dish" edge to the Dish entity.
func (dauo *DishAliasUpdateOne) SetDish(d *Dish) *DishAliasUpdateOne {
	return dauo.SetDishID(d.ID)
}

// Mutation returns the DishAliasMutation object of the builder.
func (dauo *DishAliasUpdateOne) Mutation() *DishAliasMutation {
	return dauo.mutation
}

// ClearDish clears the "dish" edge to the Dish entity.
func (dauo *DishAliasUpdateOne) ClearDish() *DishAliasUpdateOne {
	dauo.mutation.ClearDish()
	return dauo
}

// Where appends a list predicates to the DishAliasUpdate builder.
func (dauo *DishAliasUpdateOne) Where(ps ...predicate.DishAlias) *DishAliasUpdateOne {
	dauo.mutation.Where(ps...)
	return dauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (dauo *DishAliasUpdateOne) Select(field string, fields ...string) *DishAliasUpdateOne {
	dauo.fields = append([]string{field}, fields...)
	return dauo
}

// Save executes the query and returns the updated DishAlias entity.
func (dauo *DishAliasUpdateOne) Save(ctx context.Context) (*DishAlias, error) {
	return withHooks(ctx, dauo.sqlSave, dauo.mutation, dauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dauo *DishAliasUpdateOne) SaveX(ctx context.Context) *DishAlias {
	node, err := dauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (dauo *DishAliasUpdateOne) Exec(ctx context.Context) error {
	_, err := dauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dauo *DishAliasUpdateOne) ExecX(ctx context.Context) {
	if err := dauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dauo *DishAliasUpdateOne) check() error {
	if v, ok := dauo.mutation.NormalizedAliasName(); ok {
		if err := dishalias.NormalizedAliasNameValidator(v); err != nil {
			return &ValidationError{Name: "normalized_alias_name", err: fmt.Errorf(`ent: validator failed for field "DishAlias.normalized_alias_name": %w`, err)}
		}
	}
	if _, ok := dauo.mutation.DishID(); dauo.mutation.DishCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "DishAlias.dish"`)
	}
	return nil
}

func (dauo *DishAliasUpdateOne) sqlSave(ctx context.Context) (_node *DishAlias, err error) {
	if err := dauo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dishalias.Table, dishalias.Columns, sqlgraph.NewFieldSpec(dishalias.FieldID, field.TypeString))
	id, ok := dauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DishAlias.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := dauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dishalias.FieldID)
		for _, f := range fields {
			if !dishalias.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dishalias.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := dauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dauo.mutation.NormalizedAliasName(); ok {
		_spec.SetField(dishalias.FieldNormalizedAliasName, field.TypeString, value)
	}
	if dauo.mutation.DishCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dishalias.DishTable,
			Columns: []string{dishalias.DishColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dish.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dauo.mutation.DishIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dishalias.DishTable,
			Columns: []string{dishalias.DishColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dish.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DishAlias{config: dauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, dauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dishalias.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	dauo.mutation.done = true
	return _node, nil
}
