// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DishesColumns holds the columns for the "dishes" table.
	DishesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name_de", Type: field.TypeString, Unique: true},
		{Name: "name_en", Type: field.TypeString, Nullable: true},
		{Name: "occurrence_side_dishes", Type: field.TypeUUID, Nullable: true},
	}
	// DishesTable holds the schema information for the "dishes" table.
	DishesTable = &schema.Table{
		Name:       "dishes",
		Columns:    DishesColumns,
		PrimaryKey: []*schema.Column{DishesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "dishes_occurrences_side_dishes",
				Columns:    []*schema.Column{DishesColumns[3]},
				RefColumns: []*schema.Column{OccurrencesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DishAliasColumns holds the columns for the "dish_alias" table.
	DishAliasColumns = []*schema.Column{
		{Name: "alias_name", Type: field.TypeString},
		{Name: "normalized_alias_name", Type: field.TypeString},
		{Name: "dish", Type: field.TypeUUID},
	}
	// DishAliasTable holds the schema information for the "dish_alias" table.
	DishAliasTable = &schema.Table{
		Name:       "dish_alias",
		Columns:    DishAliasColumns,
		PrimaryKey: []*schema.Column{DishAliasColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "dish_alias_dishes_aliases",
				Columns:    []*schema.Column{DishAliasColumns[2]},
				RefColumns: []*schema.Column{DishesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ImagesColumns holds the columns for the "images" table.
	ImagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "image_hash", Type: field.TypeString},
		{Name: "review", Type: field.TypeUUID},
	}
	// ImagesTable holds the schema information for the "images" table.
	ImagesTable = &schema.Table{
		Name:       "images",
		Columns:    ImagesColumns,
		PrimaryKey: []*schema.Column{ImagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "images_reviews_images",
				Columns:    []*schema.Column{ImagesColumns[2]},
				RefColumns: []*schema.Column{ReviewsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// LocationsColumns holds the columns for the "locations" table.
	LocationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "external_id", Type: field.TypeInt, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// LocationsTable holds the schema information for the "locations" table.
	LocationsTable = &schema.Table{
		Name:       "locations",
		Columns:    LocationsColumns,
		PrimaryKey: []*schema.Column{LocationsColumns[0]},
	}
	// OccurrencesColumns holds the columns for the "occurrences" table.
	OccurrencesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "date", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"CONFIRMED", "APPROVED", "AWAITING_APPROVAL", "UPDATED", "PENDING_DELETION"}, Default: "AWAITING_APPROVAL"},
		{Name: "kj", Type: field.TypeInt, Nullable: true},
		{Name: "kcal", Type: field.TypeInt, Nullable: true},
		{Name: "fat", Type: field.TypeInt, Nullable: true},
		{Name: "saturated_fat", Type: field.TypeInt, Nullable: true},
		{Name: "carbohydrates", Type: field.TypeInt, Nullable: true},
		{Name: "sugar", Type: field.TypeInt, Nullable: true},
		{Name: "fiber", Type: field.TypeInt, Nullable: true},
		{Name: "protein", Type: field.TypeInt, Nullable: true},
		{Name: "salt", Type: field.TypeInt, Nullable: true},
		{Name: "price_student", Type: field.TypeInt, Nullable: true},
		{Name: "price_staff", Type: field.TypeInt, Nullable: true},
		{Name: "price_guest", Type: field.TypeInt, Nullable: true},
		{Name: "dish", Type: field.TypeUUID},
		{Name: "location", Type: field.TypeUUID},
	}
	// OccurrencesTable holds the schema information for the "occurrences" table.
	OccurrencesTable = &schema.Table{
		Name:       "occurrences",
		Columns:    OccurrencesColumns,
		PrimaryKey: []*schema.Column{OccurrencesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "occurrences_dishes_occurrences",
				Columns:    []*schema.Column{OccurrencesColumns[15]},
				RefColumns: []*schema.Column{DishesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "occurrences_locations_occurrences",
				Columns:    []*schema.Column{OccurrencesColumns[16]},
				RefColumns: []*schema.Column{LocationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ReviewsColumns holds the columns for the "reviews" table.
	ReviewsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "display_name", Type: field.TypeString, Nullable: true, Size: 32},
		{Name: "stars", Type: field.TypeInt},
		{Name: "text", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "accepted_at", Type: field.TypeTime, Nullable: true},
		{Name: "occurrence", Type: field.TypeUUID},
	}
	// ReviewsTable holds the schema information for the "reviews" table.
	ReviewsTable = &schema.Table{
		Name:       "reviews",
		Columns:    ReviewsColumns,
		PrimaryKey: []*schema.Column{ReviewsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "reviews_occurrences_reviews",
				Columns:    []*schema.Column{ReviewsColumns[7]},
				RefColumns: []*schema.Column{OccurrencesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "key", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "short_name", Type: field.TypeString, Nullable: true},
		{Name: "priority", Type: field.TypeEnum, Enums: []string{"HIDE", "LOW", "MEDIUM", "HIGH"}, Default: "HIDE"},
		{Name: "is_allergy", Type: field.TypeBool, Default: false},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// TagOccurrencesColumns holds the columns for the "tag_occurrences" table.
	TagOccurrencesColumns = []*schema.Column{
		{Name: "tag_id", Type: field.TypeString},
		{Name: "occurrence_id", Type: field.TypeUUID},
	}
	// TagOccurrencesTable holds the schema information for the "tag_occurrences" table.
	TagOccurrencesTable = &schema.Table{
		Name:       "tag_occurrences",
		Columns:    TagOccurrencesColumns,
		PrimaryKey: []*schema.Column{TagOccurrencesColumns[0], TagOccurrencesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tag_occurrences_tag_id",
				Columns:    []*schema.Column{TagOccurrencesColumns[0]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tag_occurrences_occurrence_id",
				Columns:    []*schema.Column{TagOccurrencesColumns[1]},
				RefColumns: []*schema.Column{OccurrencesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DishesTable,
		DishAliasTable,
		ImagesTable,
		LocationsTable,
		OccurrencesTable,
		ReviewsTable,
		TagsTable,
		UsersTable,
		TagOccurrencesTable,
	}
)

func init() {
	DishesTable.ForeignKeys[0].RefTable = OccurrencesTable
	DishAliasTable.ForeignKeys[0].RefTable = DishesTable
	ImagesTable.ForeignKeys[0].RefTable = ReviewsTable
	OccurrencesTable.ForeignKeys[0].RefTable = DishesTable
	OccurrencesTable.ForeignKeys[1].RefTable = LocationsTable
	ReviewsTable.ForeignKeys[0].RefTable = OccurrencesTable
	TagOccurrencesTable.ForeignKeys[0].RefTable = TagsTable
	TagOccurrencesTable.ForeignKeys[1].RefTable = OccurrencesTable
}
