// Code generated by ent, DO NOT EDIT.

package tag

import (
	"fmt"

	"github.com/mensatt/backend/internal/database/schema"
)

const (
	// Label holds the string label denoting the tag type in the database.
	Label = "tag"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "key"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldShortName holds the string denoting the short_name field in the database.
	FieldShortName = "short_name"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldIsAllergy holds the string denoting the is_allergy field in the database.
	FieldIsAllergy = "is_allergy"
	// EdgeOccurrences holds the string denoting the occurrences edge name in mutations.
	EdgeOccurrences = "occurrences"
	// OccurrenceFieldID holds the string denoting the ID field of the Occurrence.
	OccurrenceFieldID = "id"
	// Table holds the table name of the tag in the database.
	Table = "tags"
	// OccurrencesTable is the table that holds the occurrences relation/edge. The primary key declared below.
	OccurrencesTable = "tag_occurrences"
	// OccurrencesInverseTable is the table name for the Occurrence entity.
	// It exists in this package in order to avoid circular dependency with the "occurrence" package.
	OccurrencesInverseTable = "occurrences"
)

// Columns holds all SQL columns for tag fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldShortName,
	FieldPriority,
	FieldIsAllergy,
}

var (
	// OccurrencesPrimaryKey and OccurrencesColumn2 are the table columns denoting the
	// primary key for the occurrences relation (M2M).
	OccurrencesPrimaryKey = []string{"tag_id", "occurrence_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// ShortNameValidator is a validator for the "short_name" field. It is called by the builders before save.
	ShortNameValidator func(string) error
	// DefaultIsAllergy holds the default value on creation for the "is_allergy" field.
	DefaultIsAllergy bool
)

const DefaultPriority schema.TagPriority = "HIDE"

// PriorityValidator is a validator for the "priority" field enum values. It is called by the builders before save.
func PriorityValidator(pr schema.TagPriority) error {
	switch pr {
	case "HIDE", "LOW", "MEDIUM", "HIGH":
		return nil
	default:
		return fmt.Errorf("tag: invalid enum value for priority field: %q", pr)
	}
}
