// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Allergy struct {
	Abbreviation string `json:"abbreviation"`
	Name         string `json:"name"`
}

type Dish struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Image struct {
	ID          uuid.UUID      `json:"id"`
	Occurrence  uuid.UUID      `json:"occurrence"`
	DisplayName string         `json:"display_name"`
	Description sql.NullString `json:"description"`
	Votes       int32          `json:"votes"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	AcceptedAt  sql.NullTime   `json:"accepted_at"`
}

type Occurrence struct {
	ID           uuid.UUID `json:"id"`
	Dish         uuid.UUID `json:"dish"`
	Date         time.Time `json:"date"`
	PriceStudent int32     `json:"price_student"`
	PriceStaff   int32     `json:"price_staff"`
	PriceGuest   int32     `json:"price_guest"`
}

type OccurrenceAllergy struct {
	OccurrenceID        uuid.UUID `json:"occurrence_id"`
	AllergyAbbreviation string    `json:"allergy_abbreviation"`
}

type OccurrenceSideDish struct {
	OccurrenceID uuid.UUID `json:"occurrence_id"`
	DishID       uuid.UUID `json:"dish_id"`
}

type OccurrenceTag struct {
	OccurrenceID    uuid.UUID `json:"occurrence_id"`
	TagAbbreviation string    `json:"tag_abbreviation"`
}

type Review struct {
	ID          uuid.UUID      `json:"id"`
	Occurrence  uuid.UUID      `json:"occurrence"`
	DisplayName sql.NullString `json:"display_name"`
	Stars       int32          `json:"stars"`
	Text        sql.NullString `json:"text"`
	UpVotes     int32          `json:"up_votes"`
	DownVotes   int32          `json:"down_votes"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	AcceptedAt  sql.NullTime   `json:"accepted_at"`
}

type Tag struct {
	Abbreviation string `json:"abbreviation"`
	Name         string `json:"name"`
}
