name: Build & Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libvips-dev --no-install-recommends

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
