-- migrate:down
DROP TABLE IF EXISTS dish CASCADE;
DROP TABLE IF EXISTS dish_alias CASCADE;
DROP TYPE priority CASCADE;
DROP TABLE IF EXISTS tag CASCADE;
DROP TYPE review_status CASCADE;
DROP TABLE IF EXISTS occurrence CASCADE;
DROP TABLE IF EXISTS occurrence_side_dishes CASCADE;
DROP TABLE IF EXISTS occurrence_tag CASCADE;
DROP TABLE IF EXISTS review CASCADE;
DROP TABLE IF EXISTS image CASCADE;
DROP TABLE IF EXISTS location CASCADE;
